# Generated by Django 4.2 on 2025-02-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='manager_id',
            new_name='manager',
        ),
    ]
