# Generated by Django 4.2 on 2025-02-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employee_status_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé')], max_length=50),
        ),
    ]
